// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ExemplosTInjectTelegram;

{ITE} {DFMFileType} {uPrincipal.dfm}
{ITE} {RCFileType} {Win32\Debug\ExemplosTInjectTelegram_DRC.rc}

{$R 'uPrincipal.dfm' 'Form1:TForm'}
{$R 'Win32\Debug\ExemplosTInjectTelegram_DRC.res' 'Win32\Debug\ExemplosTInjectTelegram_DRC.rc'}

{$E RUS}

begin
end.
